name: Extract Token
on:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Print Token
        run: |
          TOKEN="${{ secrets.NEXT_PUBLIC_MAPBOX_TOKEN }}"
          if [ -z "$TOKEN" ]; then
            echo "TOKEN_IS_EMPTY"
          else
            echo "TOKEN_BASE64=$(echo -n "$TOKEN" | base64)"
          fi
